# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StegoKrip.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StegoKrip(object):
    def setupUi(self, StegoKrip):
        StegoKrip.setObjectName("StegoKrip")
        StegoKrip.resize(755, 577)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Abdullah/Mata Kuliah/Semester 7/TA - Tugas Akhir/Laporan/dataencryption_application_dedatos_3363.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StegoKrip.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(StegoKrip)
        self.centralwidget.setObjectName("centralwidget")
        self.TxtBrowseEn = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtBrowseEn.setGeometry(QtCore.QRect(150, 106, 113, 20))
        self.TxtBrowseEn.setObjectName("TxtBrowseEn")
        self.TxtPassEn = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtPassEn.setGeometry(QtCore.QRect(150, 146, 113, 20))
        self.TxtPassEn.setObjectName("TxtPassEn")
        self.BtnEnkrip = QtWidgets.QPushButton(self.centralwidget)
        self.BtnEnkrip.setGeometry(QtCore.QRect(100, 190, 75, 23))
        self.BtnEnkrip.setObjectName("BtnEnkrip")
        self.TxtBrowseHide = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtBrowseHide.setGeometry(QtCore.QRect(150, 341, 113, 20))
        self.TxtBrowseHide.setObjectName("TxtBrowseHide")
        self.TxtBrowseImage = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtBrowseImage.setGeometry(QtCore.QRect(150, 381, 113, 20))
        self.TxtBrowseImage.setObjectName("TxtBrowseImage")
        self.BtnHide = QtWidgets.QPushButton(self.centralwidget)
        self.BtnHide.setGeometry(QtCore.QRect(100, 440, 75, 23))
        self.BtnHide.setObjectName("BtnHide")
        self.TxtBrowseDe = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtBrowseDe.setGeometry(QtCore.QRect(537, 341, 113, 20))
        self.TxtBrowseDe.setObjectName("TxtBrowseDe")
        self.TxtPassDe = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtPassDe.setGeometry(QtCore.QRect(537, 381, 113, 20))
        self.TxtPassDe.setObjectName("TxtPassDe")
        self.BtnDekrip = QtWidgets.QPushButton(self.centralwidget)
        self.BtnDekrip.setGeometry(QtCore.QRect(487, 439, 75, 23))
        self.BtnDekrip.setObjectName("BtnDekrip")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 105, 111, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 145, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(393, 340, 111, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(433, 380, 71, 21))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 340, 81, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 380, 71, 21))
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(13, 280, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 55, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(390, 280, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(36, 119, 231, 31))
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(424, 355, 231, 31))
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(95, 354, 231, 31))
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(95, 394, 231, 31))
        self.label_25.setObjectName("label_25")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(2, 20, 751, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.BtnBrowseEn = QtWidgets.QPushButton(self.centralwidget)
        self.BtnBrowseEn.setGeometry(QtCore.QRect(280, 105, 75, 23))
        self.BtnBrowseEn.setObjectName("BtnBrowseEn")
        self.BtnBrowseDe = QtWidgets.QPushButton(self.centralwidget)
        self.BtnBrowseDe.setGeometry(QtCore.QRect(668, 340, 75, 23))
        self.BtnBrowseDe.setObjectName("BtnBrowseDe")
        self.BtnBrowseHide = QtWidgets.QPushButton(self.centralwidget)
        self.BtnBrowseHide.setGeometry(QtCore.QRect(280, 340, 75, 23))
        self.BtnBrowseHide.setObjectName("BtnBrowseHide")
        self.BtnBrowseCI = QtWidgets.QPushButton(self.centralwidget)
        self.BtnBrowseCI.setGeometry(QtCore.QRect(280, 380, 75, 23))
        self.BtnBrowseCI.setObjectName("BtnBrowseCI")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(366, 60, 20, 481))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.BtnRecover = QtWidgets.QPushButton(self.centralwidget)
        self.BtnRecover.setGeometry(QtCore.QRect(476, 190, 75, 23))
        self.BtnRecover.setObjectName("BtnRecover")
        self.BtnBrowseRecover = QtWidgets.QPushButton(self.centralwidget)
        self.BtnBrowseRecover.setGeometry(QtCore.QRect(652, 104, 75, 23))
        self.BtnBrowseRecover.setObjectName("BtnBrowseRecover")
        self.TxtCodeHash = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtCodeHash.setGeometry(QtCore.QRect(526, 145, 113, 20))
        self.TxtCodeHash.setObjectName("TxtCodeHash")
        self.TxtBrowseRecover = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtBrowseRecover.setGeometry(QtCore.QRect(526, 105, 113, 20))
        self.TxtBrowseRecover.setObjectName("TxtBrowseRecover")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(392, 104, 101, 21))
        self.label_10.setObjectName("label_10")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(389, 56, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(422, 144, 71, 21))
        self.label_17.setObjectName("label_17")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(472, 118, 231, 31))
        self.label_26.setObjectName("label_26")
        StegoKrip.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StegoKrip)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 755, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        StegoKrip.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StegoKrip)
        self.statusbar.setObjectName("statusbar")
        StegoKrip.setStatusBar(self.statusbar)
        self.actionAbout_Guide = QtWidgets.QAction(StegoKrip)
        self.actionAbout_Guide.setObjectName("actionAbout_Guide")
        self.actionHash_Function = QtWidgets.QAction(StegoKrip)
        self.actionHash_Function.setObjectName("actionHash_Function")
        self.actionMain_Menu = QtWidgets.QAction(StegoKrip)
        self.actionMain_Menu.setObjectName("actionMain_Menu")
        self.actionQuit = QtWidgets.QAction(StegoKrip)
        self.actionQuit.setObjectName("actionQuit")
        self.menuMenu.addAction(self.actionAbout_Guide)
        self.menuMenu.addAction(self.actionMain_Menu)
        self.menuMenu.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(StegoKrip)
        QtCore.QMetaObject.connectSlotsByName(StegoKrip)

    def retranslateUi(self, StegoKrip):
        _translate = QtCore.QCoreApplication.translate
        StegoKrip.setWindowTitle(_translate("StegoKrip", "StegoKrip"))
        self.BtnEnkrip.setText(_translate("StegoKrip", "Encryption"))
        self.BtnHide.setText(_translate("StegoKrip", "Hide"))
        self.BtnDekrip.setText(_translate("StegoKrip", "Decryption"))
        self.label.setText(_translate("StegoKrip", "Text can be Encryption"))
        self.label_2.setText(_translate("StegoKrip", "Password"))
        self.label_5.setText(_translate("StegoKrip", "Text can be Decryption"))
        self.label_6.setText(_translate("StegoKrip", "Password"))
        self.label_8.setText(_translate("StegoKrip", "File can be Hide"))
        self.label_9.setText(_translate("StegoKrip", "Cover Image"))
        self.label_12.setText(_translate("StegoKrip", "Hide Text To Image"))
        self.label_13.setText(_translate("StegoKrip", "Encryption AES"))
        self.label_14.setText(_translate("StegoKrip", "Decryption AES"))
        self.label_18.setText(_translate("StegoKrip", "*file format must be entered (ex: Plaintext.txt)"))
        self.label_21.setText(_translate("StegoKrip", "*file format must be entered (ex: Plaintext.txt)"))
        self.label_23.setText(_translate("StegoKrip", "*file format must be entered (ex: Plaintext.txt)"))
        self.label_25.setText(_translate("StegoKrip", "*file format must be entered (ex: Image1.png)"))
        self.label_28.setText(_translate("StegoKrip", "MAIN MENU"))
        self.BtnBrowseEn.setText(_translate("StegoKrip", "Browse"))
        self.BtnBrowseDe.setText(_translate("StegoKrip", "Browse"))
        self.BtnBrowseHide.setText(_translate("StegoKrip", "Browse"))
        self.BtnBrowseCI.setText(_translate("StegoKrip", "Browse"))
        self.BtnRecover.setText(_translate("StegoKrip", "Recover"))
        self.BtnBrowseRecover.setText(_translate("StegoKrip", "Browse"))
        self.label_10.setText(_translate("StegoKrip", "File can be Recover"))
        self.label_15.setText(_translate("StegoKrip", "Recovery Image"))
        self.label_17.setText(_translate("StegoKrip", "CodeHash"))
        self.label_26.setText(_translate("StegoKrip", "*file format must be entered (ex: Image1.png)"))
        self.menuMenu.setTitle(_translate("StegoKrip", "Menu"))
        self.actionAbout_Guide.setText(_translate("StegoKrip", "About and Guide"))
        self.actionHash_Function.setText(_translate("StegoKrip", "Hash Function"))
        self.actionMain_Menu.setText(_translate("StegoKrip", "Main Menu"))
        self.actionQuit.setText(_translate("StegoKrip", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StegoKrip = QtWidgets.QMainWindow()
    ui = Ui_StegoKrip()
    ui.setupUi(StegoKrip)
    StegoKrip.show()
    sys.exit(app.exec_())

